package com.workflow.backend;

// Feature: workflow-management-system, Property 4: New Trámite State and Reference Invariant
// Validates: Requirements 6.2, 14.1

import net.jqwik.api.*;
import net.jqwik.api.constraints.IntRange;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Property test for NumeroReferencia format invariant.
 *
 * Verifies that for any valid year and sequence number, the reference string
 * generated by TramiteService matches the expected pattern TRM-\d{4}-\d{4}.
 */
class NumeroReferenciaFormatPropertyTest {

    /**
     * Mirrors the format logic used in TramiteService.generarNumeroReferencia.
     */
    private String generarNumeroReferencia(int year, int seq) {
        return String.format("TRM-%d-%04d", year, seq);
    }

    @Property
    void numeroReferenciaMatchesExpectedFormat(
            @ForAll @IntRange(min = 2020, max = 2030) int year,
            @ForAll @IntRange(min = 1, max = 9999) int seq) {

        String referencia = generarNumeroReferencia(year, seq);

        assertThat(referencia).matches("TRM-\\d{4}-\\d{4}");
    }
}
