// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7z4igPlRM-xgb0P0uNihMadk478FWAgw',
    appId: '1:359881974140:web:2b2169d843323fc8bfc4f9',
    messagingSenderId: '359881974140',
    projectId: 'workentai-71e87',
    authDomain: 'workentai-71e87.firebaseapp.com',
    storageBucket: 'workentai-71e87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhTJ5xvjc4UmPt55BCaCPBmBXJeaIJrE',
    appId: '1:359881974140:android:c382e33145c9366bbfc4f9',
    messagingSenderId: '359881974140',
    projectId: 'workentai-71e87',
    storageBucket: 'workentai-71e87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-qNf9xY903n2E90ydp8U6hoQrV1JMC7Q',
    appId: '1:359881974140:ios:2346ee54d9cea6a5bfc4f9',
    messagingSenderId: '359881974140',
    projectId: 'workentai-71e87',
    storageBucket: 'workentai-71e87.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-qNf9xY903n2E90ydp8U6hoQrV1JMC7Q',
    appId: '1:359881974140:ios:2346ee54d9cea6a5bfc4f9',
    messagingSenderId: '359881974140',
    projectId: 'workentai-71e87',
    storageBucket: 'workentai-71e87.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7z4igPlRM-xgb0P0uNihMadk478FWAgw',
    appId: '1:359881974140:web:a0e6f29972f660c0bfc4f9',
    messagingSenderId: '359881974140',
    projectId: 'workentai-71e87',
    authDomain: 'workentai-71e87.firebaseapp.com',
    storageBucket: 'workentai-71e87.firebasestorage.app',
  );
}
