name: normalflow_mobile
description: NormalFlow — Portal del Cliente para gestión de trámites
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  shimmer: ^3.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_filex: ^4.5.0
  # Notificaciones push con FCM
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^17.2.2
  # ── Ciclo 2: Offline cache (CU-31 Opción B) ──────────────────
  sqflite: ^2.3.3+2
  path: ^1.9.0
  # ── Ciclo 2: Subir documentos desde móvil (CU-24) ───────────
  file_picker: ^8.1.2
  stomp_dart_client: ^3.0.1
  connectivity_plus: ^7.1.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
